application: gae-init
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- deferred: on
- appstats: on

libraries:
- name: jinja2
  version: latest

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /static/
  static_dir: static/

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?Icon\r
- ^lib/.*
- ^static/src/.*
- ^static/lib/.*
- ^static/dst/.*
